// ✏️ Modifiez ici le nom et les textes de votre entreprise.
export const BRAND = "Beriverse";

export const T = {
  fr: {
    top: { biz: "Beriverse Incorporation", pub: "Grand Public", sites: "Tous nos sites", media: "" },
    nav: ["A Propos", "Notre impact", "Notre expertise", "Actualités"],
    navRight: ["Marketplace", "Carrières"],
    pause: "Mettre en pause", play: "Lecture", slide: "Diapositive",
    discover: "Découvrir",
    slides: [
      { title: "Beriverse lance Corance, une plateforme innovante pour l'assurance santé", color: "a" },
      { title: "IA Agentique : Beriverse forme les entreprises dans l'automatisation de leurs processus", color: "b" },
      { title: "Beriverse Academy : apprendre le code, l'IA et les métiers du numérique pour tous", color: "c" },
    ],
    about: "est une société dans les secteurs de la technologie et de l'éducation dont la mission est d'accroître les capacité de tous. Nous proposons des services aux entreprises et au grand public, notamment dans les domaines de l'intelligence artificielle, de la formation et du développement d'applications. Notre objectif est de créer un impact positif et durable dans la société grâce à l'innovation et à l'éducation.",
    expTitle: "Notre expertise",
    tabs: ["Entreprises", "Grand public"],
    biz: [
      ["Technology Consulting", "Accompagnement stratégique pour la transformation digitale de votre entreprise."],
      ["Formation", "Programmes sur mesure pour développer les compétences de vos équipes."],
      ["Edge AI", "Exploitez vos données pour prendre des décisions plus rapides et automatiser vos processus."],
    ],
    pub: [
      ["Beriverse Academy", "Cours en ligne et en présentiel, du niveau débutant au niveau professionnel."],
      ["English Center", "Apprendre l'anglais à votre rythme, sur mobile, même avec une connexion faible."],
      // ["Applications Grand Public", "Applications mobiles et web pour faciliter la vie quotidienne des familles."],
    ],
    figTitle: "Notre impact en chiffres",
    figs: [["1000+", "apprenants formés"], ["25+", "entreprises accompagnées"], ["3", "années d'existence"], ["100+", "collaborateurs"]],
    newsTitle: "Dernières actualités",
    news: [
      ["Technologie", "Lancement de la plateforme Corance pour les assurances", "12 Septembre 2026"],
      ["Education", "OpenClass 2026-2027 : L'IA la nouvelle ère du numérique", "28 août 2026"],
      ["Entreprises", "Lancement de la division English Center", "05 Octobre 2026"],
    ],
    more: "Lire la suite",
    careersTitle: "Rejoignez Beriverse",
    careersText: "Ingénieurs, formateurs, commerciaux : Inspirons et Tranformons le monde.",
    careersBtn: "Voir les offres",
    contactTitle: "Une question ? Écrivez-nous",
    name: "Votre nom", email: "Votre e-mail", msg: "Votre message", send: "Envoyer", sent: "Message envoyé. Nous vous répondons sous 48 h.",
    foot: ["Notre groupe", "Notre impact", "Notre expertise", "Actualités", "Carrières"],
    rights: "Tous droits réservés.",
  },
  en: {
    top: { biz: "Beriverse Inc.", pub: "Beriverse Consumer", sites: "All our sites", media: "Media library", conf: "Academy" },
    nav: ["About", "Our impact", "Our expertise", "Our news"],
    navRight: ["Finance", "Press", "Careers"],
    pause: "Pause", play: "Play", slide: "Slide",
    discover: "Discover",
    slides: [
      { title: "Beriverse launches Corance, a innovative platform for health insurances", color: "a" },
      { title: "Agentic AI: Beriverse trains companies in process automation.", color: "b" },
      { title: "Beriverse Academy: learning coding, AI, and digital careers for everyone.", color: "c" },
    ],
    about: "is a company in the technology and education sectors whose mission is to enhance everyone's capabilities. We offer services to businesses and the general public, particularly in the fields of artificial intelligence, training, and application development. Our goal is to create a positive and lasting impact in society through innovation and education.",
    expTitle: "Our expertise",
    tabs: ["Business", "Consumers"],
    biz: [
      ["Consulting", "Strategic guidance for your company's digital transformation."],
      ["Edge AI", "Leverage your data to make faster decisions and automate your processes."],
      ["Professional training", "Tailor-made programs to develop your teams' skills."],
    ],
    pub: [
      ["Beriverse Academy", "Online and in-person courses, from beginner to professional."],
      ["English Center", "Learn English at your own pace, on mobile, even with a low connection."],
      ["Apps", "Mobile and web applications to make everyday life easier for families."],
    ],
    figTitle: "Our impact in numbers",
    figs: [["1,000+", "learners trained"], ["25+", "companies supported"], ["3", "Years of existence"], ["100", "employees"]],
    newsTitle: "Latest news",
    news: [
      ["Technology", "Launch of the Corance platform for the insurance sector", "Sep 12, 2026"],
      ["Education", "OpenClass 2026-2027: AI – The New Digital Era", "Aug 28, 2026"],
      ["Business", "Launch of the English Center division", "Oct 5, 2026"],
    ],
    more: "Read more",
    careersTitle: "Join Beriverse",
    careersText: "Engineers, trainers, sales: let's build the technology and education of tomorrow together.",
    careersBtn: "See openings",
    contactTitle: "Questions? Write to us",
    name: "Your name", email: "Your email", msg: "Your message", send: "Send", sent: "Message sent. We will reply within 48 hours.",
    foot: ["Our Group", "Our impact", "Our expertise", "Our news", "Finance", "Press", "Careers"],
    rights: "All rights reserved.",
  },
};
