// ✏️ Contenu des pages Actualités (articles) et Carrières. L'ordre des articles = l'ordre de t.news dans content.js.
export const EXTRA = {
  fr: {
    all: "Toutes", allNews: "Toutes les actualités", back: "← Toutes les actualités", home: "Accueil",
    newsTitle: "Nos Actualités", newsIntro: "Annonces, lancements et temps forts de Beriverse.",
    others: "À lire aussi", notFound: "Cet article n'existe pas.",
    newsBody: [
      ["Beriverse annonce le lancement de Corance, une plateforme pensée pour simplifier la gestion de l'assurance santé : souscription, suivi des remboursements et relation client réunis au même endroit.",
       "Conçue avec des professionnels du secteur, Corance s'appuie sur l'automatisation et l'intelligence artificielle pour réduire les délais de traitement et améliorer l'expérience des assurés."],
      ["L'édition 2026-2027 d'OpenClass est consacrée à l'intelligence artificielle et à son rôle dans la nouvelle ère du numérique. Ateliers, conférences et démonstrations sont au programme.",
       "Cet événement s'adresse aux étudiants, aux professionnels et aux entreprises qui souhaitent comprendre et adopter l'IA dans leurs métiers."],
      ["Beriverse crée la division English Center pour aider les particuliers et les entreprises à progresser en anglais, avec des parcours en ligne et en présentiel.",
       "Les cours s'adaptent au niveau et au rythme de chacun, y compris sur mobile et avec une connexion limitée."],
    ],
    careersTitle: "Carrières", careersIntro: "Inspirons et transformons le monde. Rejoignez une équipe qui construit la technologie et l'éducation de demain.",
    whyTitle: "Pourquoi nous rejoindre",
    why: [["Impact réel", "Vos projets touchent des milliers d'apprenants et d'entreprises."], ["Apprendre en continu", "Accès à Beriverse Academy et à des formations internes."], ["Équipe ambitieuse", "Une culture d'innovation, d'entraide et de responsabilité."]],
    jobsTitle: "Nos offres", apply: "Postuler",
    email: "carrieres@beriverse.fr", subject: "Candidature : ",
    jobs: [
      { slug: "ingenieur-ia", title: "Ingénieur(e) IA", type: "CDI", place: "Abidjan", desc: "Concevoir et déployer des solutions d'IA et d'automatisation pour nos clients.",
        missions: ["Analyser les besoins des clients et concevoir des solutions d'IA", "Développer, tester et déployer des modèles et des agents", "Documenter et former les équipes utilisatrices"],
        profile: ["Bac+5 en informatique, data ou équivalent", "Maîtrise de Python et des outils d'IA", "Goût pour le travail en équipe et la pédagogie"] },
      { slug: "formateur-developpement-web", title: "Formateur / Formatrice en développement web", type: "CDD", place: "Abidjan / En ligne", desc: "Animer des cours de code et accompagner les apprenants de Beriverse Academy.",
        missions: ["Animer des sessions de formation en ligne et en présentiel", "Préparer les supports et les exercices pratiques", "Suivre la progression des apprenants"],
        profile: ["Expérience en développement web (HTML, CSS, JavaScript, React)", "Capacité à expliquer simplement", "Première expérience de formation appréciée"] },
      { slug: "developpement-commercial", title: "Chargé(e) de développement commercial", type: "CDI", place: "Abidjan", desc: "Développer le portefeuille d'entreprises clientes et suivre les partenariats.",
        missions: ["Prospecter et présenter nos offres aux entreprises", "Négocier et suivre les contrats et partenariats", "Remonter les besoins du marché aux équipes produit"],
        profile: ["Bac+3 minimum, première expérience commerciale", "Aisance relationnelle et sens du résultat", "Intérêt pour la technologie et l'éducation"] },
    ],
    missions: "Missions", profileTitle: "Profil recherché", backJobs: "← Toutes les offres", viewJob: "Voir l'offre", jobNotFound: "Cette offre n'existe plus.",
    spont: "Aucune offre ne vous correspond ?", spontText: "Envoyez-nous une candidature spontanée.",
  },
  en: {
    all: "All", allNews: "All news", back: "← All news", home: "Home",
    newsTitle: "News", newsIntro: "Announcements, launches and highlights from Beriverse.",
    others: "Also read", notFound: "This article does not exist.",
    newsBody: [
      ["Beriverse announces the launch of Corance, a platform designed to simplify health insurance management: subscription, claims tracking and customer relations in one place.",
       "Built with industry professionals, Corance relies on automation and artificial intelligence to cut processing times and improve the policyholder experience."],
      ["The 2026-2027 OpenClass edition focuses on artificial intelligence and its role in the new digital era. Workshops, talks and demos are on the program.",
       "The event is open to students, professionals and companies who want to understand and adopt AI in their work."],
      ["Beriverse creates the English Center division to help individuals and companies improve their English, with online and in-person programs.",
       "Courses adapt to each learner's level and pace, including on mobile and with a limited connection."],
    ],
    careersTitle: "Careers", careersIntro: "Let's inspire and transform the world. Join a team building the technology and education of tomorrow.",
    whyTitle: "Why join us",
    why: [["Real impact", "Your projects reach thousands of learners and companies."], ["Keep learning", "Access to Beriverse Academy and internal training."], ["Ambitious team", "A culture of innovation, mutual support and ownership."]],
    jobsTitle: "Open positions", apply: "Apply",
    email: "carrieres@beriverse.fr", subject: "Application: ",
    jobs: [
      { slug: "ingenieur-ia", title: "AI Engineer", type: "Full-time", place: "Abidjan", desc: "Design and deploy AI and automation solutions for our clients.",
        missions: ["Analyze client needs and design AI solutions", "Build, test and deploy models and agents", "Document and train user teams"],
        profile: ["Master's degree in computer science, data or equivalent", "Strong Python and AI tooling skills", "Team spirit and teaching mindset"] },
      { slug: "formateur-developpement-web", title: "Web Development Trainer", type: "Fixed-term", place: "Abidjan / Online", desc: "Teach coding courses and support Beriverse Academy learners.",
        missions: ["Lead online and in-person training sessions", "Prepare materials and hands-on exercises", "Track learner progress"],
        profile: ["Web development experience (HTML, CSS, JavaScript, React)", "Ability to explain things simply", "Prior training experience is a plus"] },
      { slug: "developpement-commercial", title: "Business Development Officer", type: "Full-time", place: "Abidjan", desc: "Grow our portfolio of business clients and manage partnerships.",
        missions: ["Prospect and present our offers to companies", "Negotiate and follow up contracts and partnerships", "Feed market needs back to product teams"],
        profile: ["Bachelor's degree minimum, first sales experience", "Strong interpersonal skills and drive for results", "Interest in technology and education"] },
    ],
    missions: "Responsibilities", profileTitle: "Your profile", backJobs: "← All positions", viewJob: "View position", jobNotFound: "This position no longer exists.",
    spont: "No position fits?", spontText: "Send us a spontaneous application.",
  },
};
